### ISSUE TITLE
'execute' is not supported in this standalone mysql module

### ISSUE THREAD

**Issue by michaelgoin** [newrelic/node-newrelic-mysql#59]
It looks like when 'execute' support was added in 2019 to the main agent mysql instrumentation, this module was not updated and we didn't have an issue to capture.

As such, a couple recent attempts to use mysql2/promise by customers and internal folks have had issues because they are using this function.

Whether we keep this module or merge back into the main agent, we should ensure this functionality works with mysql2/promise usages.

Here's one instance: https://github.com/newrelic/node-newrelic-mysql/issues/47#issuecomment-901791276

Main agent reference: 
https://github.com/newrelic/node-newrelic/blob/main/lib/instrumentation/mysql.js#L134-L136
https://github.com/newrelic/node-newrelic/commit/d64f7de618b873246e4da77bd24bcf25c3b2e060

Effort: Small

**Comment by bizob2828** [comment]
I tried to add a test with the ignite folks to demonstrate failure and it passed.  It looks like the standalone module `@newrelic/mysql` has the agent as a dev/peer dep and it's running the agent mysql instrumentation instead of the local instrumentation.  If I comment out the mysql registration in agent only the `mysql2/promise` tests works.  If I try to add tests for mysql2/promises for the connection pool I get issues where the transactions are not in context.  I'm just noting this as there may be prework necessary to actually fix and test reliably.
